### ISSUE TITLE
Dark theme doesn't work in angular

### ISSUE THREAD

**Issue by anonysoul** [sweetalert2/sweetalert2-themes#101]
## Current behavior

Dark theme doesn't work

## Expected behavior

Use dark theme.

## Live demo 

https://github.com/cliesh/editor/tree/galilee

Run the demo:
```
npm run start:ng
npm run start:electron
```

**Comment by limonte** [comment]
```diff
- import Swal from 'sweetalert2';
+ import Swal from 'sweetalert2/dist/sweetalert2.js';
```

**Comment by anonysoul** [comment]
Thank you for your response.
