### ISSUE TITLE
success icon is bugged (dark mode theme)

### ISSUE THREAD

**Issue by imightknoiw** [sweetalert2/sweetalert2-themes#108]
## Current behavior
The success icon's background is white (the popup is dark theme)
## Expected behavior
success icon matches popup background
## Live demo 
![screenshot](https://i.ibb.co/HTx08R5/Screenshot-2022-10-21-12-39-15-PM.png)

**Comment by limonte** [comment]
A screenshot isn't a live demo.

Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
