### ISSUE TITLE
Bootstrap theme

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-themes#12]
Bootstrap seems to be an extremely popular framework.

Let's copy-paste these styles to `bootstrap-4` theme: https://getbootstrap.com/docs/4.0/components/modal/

**Comment by limonte** [comment]
If anybody is willing to help, here's the quick start guide: https://github.com/sweetalert2/sweetalert2-themes#contributing

**Comment by limonte** [comment]
Done in #19

**Comment by varunsridharan** [comment]
@limonte i love your project :-) and i am happy to contribute in a way i could i am not a good designer but i can help you by extracting bootstrap css to make a theme. or if you could provide me an example. i can do it

**Comment by gverni** [comment]
@varunsridharan thanks for willing to help. To create the theme just follow the instructions [here](https://github.com/sweetalert2/sweetalert2-themes#contributing). Once you created a new theme, you need to _tweak_ the existing SCSS variable (you can find them defined in [variable.scss](https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss)) in the  scss file that gets created for your specific theme. You can have a look at the themes already developed for this project for some example of how to do that (e.g. [dark.scss](https://github.com/sweetalert2/sweetalert2-themes/blob/master/dark/dark.scss)). If you think you need new variables feel free to give us a shout or open a PR on the main Sweetalert2 repo.  

I'm currently (slowly) developing the material theme (see #21), if you want to see a new theme under development.

**Comment by varunsridharan** [comment]
@gverni well i am actually waiting for response from @limonte  for the issue 
https://github.com/sweetalert2/sweetalert2/issues/1611
in case if @limonte decided to add it. there will be a slight change to the theme module in SweatAlert2

**Comment by limonte** [comment]
I don't see how implementing the Bootstrap theme depends on https://github.com/sweetalert2/sweetalert2/issues/1611

@varunsridharan if you're willing to proceed with the implementation please proceed with the clear instructions provided by @gverni in https://github.com/sweetalert2/sweetalert2-themes/issues/12#issuecomment-498565385

**Comment by REJack** [comment]
@limonte I would create the bootstrap-4 theme, if it is still open 😄

**Comment by varunsridharan** [comment]
@REJack this is still open. and i am already trying to understand on how it can be done.

May be if you want you could work on it and send a pull request. 
I am still checking the files and trying to understand. which means i am not yet started the work 😞

**Comment by REJack** [comment]
Ok sweet, I'll create soon a PR draft like @gverni did.

**Comment by limonte** [comment]
Great news! Please go ahead @REJack I would be happy to review your work!
