### ISSUE TITLE
sweetalert2 popup is showing in different pages/route

### ISSUE THREAD

**Issue by Kaisar-byte** [sweetalert2/sweetalert2-themes#125]
This is coderkaisar, working on MERN project. Recently, I have developed an MERP web application in which are containing resale market home page, dashboard, seller dashboard, buyer dashboard and admin dashboard. Issue is when I am implementing swal.fire() in seller or buyer dashboard sweetalert2 pop up is showing in home page instead of dashboard pages. I have tried different sources as well as chatgpt but failed to fixed it. So I need solution from your side.

With regards,
Kaisar Hamid
CoderKaisar
Web developer
BD

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
