### ISSUE TITLE
Bulma theme

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-themes#13]
Specs: https://bulma.io/documentation/components/modal/ (see the "Modal card" example)

**Comment by limonte** [comment]
If anybody is willing to help, here's the quick start guide: https://github.com/sweetalert2/sweetalert2-themes#contributing

**Comment by PikadudeNo1** [comment]
I'm interested in doing this. Questions before I start:

1. Is compatibility with Bulma's modifiers and/or variables desired?
2. Is it acceptable to make Bulma a peer/dev dependency of this package?

**Comment by gverni** [comment]
Hi @PikadudeNo1 thanks for willing to help! This is mostly a CSS theme. So the effort is about changing existing sweetalert SCSS variables as well as adding some css directly. So I think adding Bulma as peer dependency should not be possible. In the case of the material-ui for example, we are trying to make all the styling through css, even though there are out there packages that changes the styling using a mix of js/css.  

On the other hand I'm not an expert of Bulma, so I'm not even sure it's possible to style the modal just with css. 

I know I'm not answering your questions, but I hope I'm giving you some background information about this project.

**Comment by PikadudeNo1** [comment]
@gverni It appears you assumed Bulma is part JavaScript, but its source is pure SCSS.

**Comment by limonte** [comment]
Thank you @PikadudeNo1! We'd be happy to review your PR!

> Is compatibility with Bulma's modifiers and/or variables desired?
I do not have any strong opinion on this, but I'd assume that making it without the compatibility will be easier. If so, I'd prefer to go without the compatibility with Bulma's modifiers and/or variables.

> Is it acceptable to make Bulma a peer/dev dependency of this package?

I agree with @gverni let's just copy-paste variables without introducing the additional dependency.

**Comment by gverni** [comment]
> @gverni It appears you assumed Bulma is part JavaScript, but its source is pure SCSS.

That goes a long way to explain how much I know about Bulma 😉

**Comment by PikadudeNo1** [comment]
I am formally abandoning this and encouraging other contributors to step up to do it. Thanks for you support in the initial stages.

**Comment by limonte** [comment]
Thank you for notifying us @PikadudeNo1 

Can I ask you did you abandon this because of lack of your time or because you were unhappy with  the themeability of SweetAlert2?

**Comment by PikadudeNo1** [comment]
Lack of time.

**Comment by tiagostutz** [comment]
Hi guys!
I never worked with Bulma before, but I'm interested taking this issue.

Can I take this issue or is someone already working on it?

**Comment by limonte** [comment]
@tiagostutz nobody is working on this theme, please go ahead!

While working on the theme, please report to `sweetalert2` repo if you'll be missing some Sass variables. In that case we should first add the missing variables to https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss and then proceed with the theme.

**Comment by tiagostutz** [comment]
Nice, understood!

I'm taking a look at Bulma now and then starting with the theme here. 

Thanks! =)
