### ISSUE TITLE
Material UI theme 

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-themes#14]
Specs: https://next.material-ui.com/demos/dialogs/

The theme name should be `material-ui`

**Comment by limonte** [comment]
If anybody is willing to help, here's the quick start guide: https://github.com/sweetalert2/sweetalert2-themes#contributing

**Comment by gverni** [comment]
I initiated a draft PR for material theme UI. I'm not a _material ui_ expert so feel free to contribute on that PR.

**Comment by Yairsaenz7** [comment]
Hi gverni, I forked the sweetalert2-themes code and I switched to your branch. I see your changes and it is looking great. Is there something in particular I could help with?

**Comment by gverni** [comment]
Thanks @Yairsaenz7, glad you like it! I was going to tackle `checkbox`es next, based on: 

* https://material.io/design/components/selection-controls.html#checkboxes

You can have a look at some implementations here: 

* https://material-components.github.io/material-components-web-catalog/#/component/checkbox
* https://material-ui.com/components/checkboxes/

The main aim of this effort is to use as many SCSS variables as you can. If you don't have a variable that is useful for your styling, then you can add SCSS code and we may add the variable(s) later on once this implementation is over.

Let me know if you want to do the checkboxes and I'll do something else.

**Comment by Yairsaenz7** [comment]
Gotcha, checkbox sounds fun.  Let me try that. Thanks

**Comment by gverni** [comment]
Thanks @Yairsaenz7 for letting me know! I'll move on to doing the `slider` then. Let's continue the conversation on the PR if you need any help.
