### ISSUE TITLE
Borderless theme

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-themes#15]
The inspiration can be taken from the Supervan theme from here: https://craftpip.github.io/angular-confirm/

The name of the theme is to be discussed. For now, it's `borderless` butI'm opened for better naming suggestions.

![image](https://user-images.githubusercontent.com/6059356/57073221-1a8ae200-6ce9-11e9-96a3-816ef035772f.png)

**Comment by limonte** [comment]
If anybody is willing to help, here's the quick start guide: https://github.com/sweetalert2/sweetalert2-themes#contributing

**Comment by Kalvisan** [comment]
This one looks cool. I should give it a try. Maybe you got some more images/ideas about design?

**Comment by limonte** [comment]
Great! Please go ahead @Kalvisan

As I understand correctly:

- the popup background (`$swal2-background`) should be set to `transparent` 
- the backdrop background color `$swal2-backdrop` should be set to `rgba(54, 70, 93, .99)`
- the popup text color should be changed to white
- etc.

**Comment by Kalvisan** [comment]
Added pull request: https://github.com/sweetalert2/sweetalert2-themes/pull/19

**Comment by Kalvisan** [comment]
You closed the wrong one!

And what about Toast style. You changed in commit 5820967 my workaround to fix same font color as background color. Same for select style.

**Comment by limonte** [comment]
> You closed the wrong one!

Oops, reopened that one :)

> And what about Toast style. You changed in commit 5820967 my workaround to fix same font color as background color. 

I don't see much value in borderless toasts, let's ignore theme in borderless theme.

> Same for select style.

Oops, that's a mistake, I'll fix that :+1: 

PS: https://sweetalert2.github.io/ - the borderless theme is available:

![image](https://user-images.githubusercontent.com/6059356/57513468-f9447a00-7316-11e9-9088-ae45945fa72f.png)

**Comment by Kalvisan** [comment]
Borderless theme broke Toast modal.

**Comment by limonte** [comment]
> Borderless theme broke Toast modal.

Fixed now: 

![image](https://user-images.githubusercontent.com/6059356/57515113-8fc66a80-731a-11e9-9cf0-d23ddbc9c0fb.png)

**Comment by limonte** [comment]
Great work, thank you so much for your cooperation @Kalvisan
