### ISSUE TITLE
Got error while executing create-new-theme script

### ISSUE THREAD

**Issue by Kalvisan** [sweetalert2/sweetalert2-themes#17]
#15 
So I tried to create a new theme by using your create-new-theme.js script and after executing got error. After an error, it still created a folder and files inside.

Steps to produce:
1. Windows 10
2. Fork `sweetalert2` project
3. `git clone` inside a new folder
4. `npm i`
5. `npm audit fix` just to be safe I run audit fix
6. executed command: `npm run create-new-theme borderless` 

![image](https://user-images.githubusercontent.com/8895580/57143975-a9226080-6dc8-11e9-93a6-6ce9f167c335.png)

**Comment by limonte** [comment]
Thanks for reporting @Kalvisan! I should've tested on Windows before merging that feature. I'll fix it asap (approx in a couple of hours) so you can start with the borderless theme :rocket:

**Comment by limonte** [comment]
btw. the theme files should be created, you just need to run `npm start` and navigate to `http://localhost:3000/<theme-name>` to start the development

**Comment by limonte** [comment]
Fixed in 1372e041c7eecb4a43b86e6a04a0eed2650044d8
