### ISSUE TITLE
Themes not working on Production

### ISSUE THREAD

**Issue by kls551** [sweetalert2/sweetalert2-themes#30]
I am trying to use sweetalert2 dark theme on a react website, but it is not working on production.
Import in App.jsx: `import '@sweetalert2/themes/dark';`
Import in components: `import Swal from 'sweetalert2';`

I've tried importing separately as per doc but still does not work on production. It works completely fine on development. The production is the static file served through `react-scripts build`.
Any help would be appreciated!

**Comment by limonte** [comment]
As per [docs](https://github.com/sweetalert2/sweetalert2-themes#usage):

```
import Swal from 'sweetalert2/src/sweetalert2.js'
```

It's important to import from `sweetalert2/src/sweetalert2.js`, because importing from `sweetalert2` will import the default styles which will conflict with the included theme.

**Comment by kls551** [comment]
It works. Need to change all the imports, I was changing one single component and testing it.
Thanks!

**Comment by definaru** [comment]
This doesn't work for React JS (Next.js) !

> \node_modules\sweetalert2\src\sweetalert2.js:1
> import SweetAlert from './SweetAlert.js'
> ^^^^^^

`SyntaxError: Cannot use import statement outside a module`
