### ISSUE TITLE
Borderless, Bootstrap 4, Dark, Default, & Material UI theme's check mark exceeding bounds

### ISSUE THREAD

**Issue by RatherLogical** [sweetalert2/sweetalert2-themes#37]
References: https://github.com/sweetalert2/sweetalert2/issues/1800, https://github.com/sweetalert2/sweetalert2/issues/1799, https://github.com/sweetalert2/sweetalert2/issues/1798, & https://github.com/sweetalert2/sweetalert2/issues/1797

The Borderless, Bootstrap 4, Dark, Default, & Material UI theme's check marks are exceeding bounds.

Obviously these are related to the other issues I opened, should be a simple fix to rebase the base scss with master from the main repo. Not sure how the dev workflow is in this repo though.

![image](https://user-images.githubusercontent.com/39105734/68252105-98aaa700-fff2-11e9-9ab7-a3dd86ea56a1.png)

https://codepen.io/RatherLogical/pen/GRRxMbr?&editable=true

**Comment by limonte** [comment]
Thank you for reporting @RatherLogical!

Fixed now!
