### ISSUE TITLE
Dark theme: backdrop isn't transparent

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-themes#5]
Live demo: https://sweetalert2.github.io

![image](https://user-images.githubusercontent.com/6059356/56973855-5a7d8800-6b76-11e9-8b39-596d9b68658a.png)

**Comment by gverni** [comment]
Sorry @limonte. Forgot to check this one. In the PR I also added a text in the index page so we can test it for the future themes.
