### ISSUE TITLE
Added Dark Theme CSS But SweetAlert2 shows Inline CSS.

### ISSUE THREAD

**Issue by jsahani** [sweetalert2/sweetalert2-themes#56]
Hi,

I have added dark theme css in my header and removed default sweetalert.css but when i try to check the result i notice that sweetalert is taking style from "inline" not from the dark.css theme file.

Screenshot:- https://yadi.sk/d/Dg441tUlkcX60w

Thanks

**Comment by limonte** [comment]
remove this line

![image](https://user-images.githubusercontent.com/6059356/82041186-6fa95400-96b0-11ea-8d8c-1ab013bd3de7.png)
