### ISSUE TITLE
Showing a SweetAlert in fullscreen

### ISSUE THREAD

**Issue by vnihoul77** [sweetalert2/sweetalert2-themes#95]
We're looking to display a SweetAlert popup in fullscreen.
Here's what we tried so far:

CSS

    .fullscreen-swal{
    		z-index: 9999 !important;
            width:100vw !important;
            height:100vh !important;
      		}

JS

        customClass: "fullscreen-swal",
        autoHeight: false

The popup is not showing almost (70%) fullscreen, so it's bigger but not fullscreen.
What am I missing?

**Comment by limonte** [comment]
```js
Swal.fire({
  grow: 'fullscreen'
})
```

**Comment by vnihoul77** [comment]
Thanks for your answer, however using this parameter still leaves borders/space around the modal.
Screenshot: https://imgur.com/a/FTR9xXq
